// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type CreateMovieInput struct {
	Title       string   `json:"title"`
	Description string   `json:"description"`
	Director    string   `json:"director"`
	Cast        []string `json:"cast"`
	Genre       string   `json:"genre"`
	Runtime     float64  `json:"runtime"`
	Released    int      `json:"released"`
	Img         string   `json:"img"`
}

type CreateRatingInput struct {
	MovieID string `json:"movieId"`
	Message string `json:"message"`
	Star    int    `json:"star"`
}

type Movie struct {
	ID          string    `json:"id"`
	Title       string    `json:"title"`
	Description string    `json:"description"`
	Director    string    `json:"director"`
	Cast        []string  `json:"cast"`
	Genre       string    `json:"genre"`
	Runtime     float64   `json:"runtime"`
	Released    int       `json:"released"`
	Img         string    `json:"img"`
	Ratings     []*Rating `json:"ratings"`
}

type Rating struct {
	ID        string    `json:"id"`
	MovieID   string    `json:"movieId"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
	Message   string    `json:"message"`
	Star      int       `json:"star"`
}

type UpdateMovieInput struct {
	ID          string   `json:"id"`
	Title       string   `json:"title"`
	Description string   `json:"description"`
	Director    string   `json:"director"`
	Cast        []string `json:"cast"`
	Genre       string   `json:"genre"`
	Runtime     float64  `json:"runtime"`
	Released    int      `json:"released"`
	Img         string   `json:"img"`
}

type UpdateRatingInput struct {
	ID      string `json:"id"`
	Message string `json:"message"`
	Star    int    `json:"star"`
}
